/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.MusicaDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Models.Genero;
import Models.GeneroPreferido;
import Models.Musica;
import static java.lang.Double.parseDouble;


/**
 *
 * @author win
 */
public class MusicaView extends javax.swing.JFrame {
    
    /**
     * Creates new form MusicaView
     */
    public MusicaView() {
        initComponents();
        
        MusicaDAO maindao = new MusicaDAO();
        maindao.limpaGeneroPreferido();
        LoadComboBoxGen();
        LoadTabelaGen();
        LoadTabelaRecomendada();
        LoadTabelaAvaliacao();
        ManipulacaoInterfase("Navegar");
        
        setLocationRelativeTo(null);
        
        TextField_outros.setEnabled(false);
        ComboBox_gen2.setEnabled(false);
        
        
        
        
        
        
    }
    public void LoadComboBoxGen(){
        MusicaDAO dao = new MusicaDAO();
        dao.limpagenero();
        LoadTabelaGen();
        
        for(Genero g: dao.readgen()){
            ComboBox_generos.addItem(g.toString());
            ComboBox_recomendacao.addItem(g.toString());
        }
    }
    
    
    public void LoadTabelaGen(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{""},0);
        MusicaDAO dao = new MusicaDAO();
        for(GeneroPreferido ng: dao.readGenPref(Text_usuario.getText())){
            modelo.addRow(new Object[]{
                ng.getGenero()
            });
        }
            
        Tabela_genero.setModel(modelo);
    }
    
    
    
    public void LoadTabelaRecomendada(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Música","Nota"},0);
        MusicaDAO dao = new MusicaDAO();
        
        for(Musica i: dao.readRecomendadas(ComboBox_recomendacao.getSelectedItem().toString(),Text_usuario.getText())){
            
            modelo.addRow(new Object[]{
                i.getMusica(),
                i.getNota()
            });
        }
        
        Tabela_recomendados.setModel(modelo);
    }
    
     public void LoadTabelaAvaliacao(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"Músicas", "Notas"},0);
        MusicaDAO dao = new MusicaDAO();
        
        for(Musica i: dao.readAvaliacao(Text_usuario.getText())){
            
            modelo.addRow(new Object[]{
                i.getMusica(),
                i.getNota()
            });
        }
        
        Tabela_Avaliacao.setModel(modelo);
    }
    
    public void ManipulacaoInterfase (String modo){
        switch(modo){
            case "Navegar":
                    ComboBox_generos.setEnabled(false);
                    btn_add_gen.setEnabled(false);
                    btn_cancelar_gen.setEnabled(false);
                    btn_excluir_gen.setEnabled(false);
                    btn_novo_gen.setEnabled(true);
                    ComboBox_generos.setSelectedIndex(0);
                break;
            case "Novo":
                    ComboBox_generos.setEnabled(true);
                    btn_add_gen.setEnabled(true);
                    btn_cancelar_gen.setEnabled(true);
                    btn_excluir_gen.setEnabled(false);
                    btn_novo_gen.setEnabled(false);
                break;
            case "Excluir":
                    ComboBox_generos.setEnabled(false);
                    btn_add_gen.setEnabled(false);
                    btn_cancelar_gen.setEnabled(false);
                    btn_excluir_gen.setEnabled(false);
                    btn_novo_gen.setEnabled(true);
                    btn_excluir_gen.setEnabled(true);
                break;
            case "Cancelar":
                    ComboBox_generos.setEnabled(false);
                    btn_add_gen.setEnabled(false);
                    btn_cancelar_gen.setEnabled(false);
                    btn_novo_gen.setEnabled(true);
                    
                break;
            default: System.out.println("Modo Invalido...");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Text_usuario = new javax.swing.JLabel();
        jPanel_nova_musica = new javax.swing.JPanel();
        label_nome = new javax.swing.JLabel();
        label_gen1 = new javax.swing.JLabel();
        TextField_nome = new javax.swing.JTextField();
        TextField_outros = new javax.swing.JTextField();
        btn_salvar_musica = new javax.swing.JButton();
        btn_limpar_musica = new javax.swing.JButton();
        ComboBox_gen1 = new javax.swing.JComboBox<>();
        Label_outros = new javax.swing.JLabel();
        btn_selc_gen2 = new javax.swing.JRadioButton();
        ComboBox_gen2 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela_genero = new javax.swing.JTable();
        btn_novo_gen = new javax.swing.JButton();
        btn_excluir_gen = new javax.swing.JButton();
        btn_atualizar_gen = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        ComboBox_generos = new javax.swing.JComboBox<>();
        btn_add_gen = new javax.swing.JButton();
        btn_cancelar_gen = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabela_Avaliacao = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        TextField_nota = new javax.swing.JTextField();
        btn_avaliar_musica = new javax.swing.JButton();
        TextField_musica_avaliar = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabela_recomendados = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        btn_adicionar_musica = new javax.swing.JButton();
        TextField_musica_adicionar = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        ComboBox_recomendacao = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });
        jTabbedPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane1FocusGained(evt);
            }
        });

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Text_usuario.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(Text_usuario)))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Text_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("Início", jPanel1);

        label_nome.setText("NOME DA MÚSICA:");

        label_gen1.setText("GÊNERO1:");

        TextField_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_nomeActionPerformed(evt);
            }
        });

        btn_salvar_musica.setText("Salvar");
        btn_salvar_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salvar_musicaActionPerformed(evt);
            }
        });

        btn_limpar_musica.setText("Limpar");
        btn_limpar_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpar_musicaActionPerformed(evt);
            }
        });

        ComboBox_gen1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Axé", "Blues", "Country", "Eletrônica", "Forró", "Funk", "Gospel", "Hip Hop", "Jazz", "MPB", "Música clássica", "Pagode", "Pop", "Rap", "Reggae", "Rock", "Samba", "Sertanejo", "Trap", "Outros" }));
        ComboBox_gen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_gen1ActionPerformed(evt);
            }
        });

        Label_outros.setText("OUTROS:");

        btn_selc_gen2.setText("GÊNERO2:");
        btn_selc_gen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_selc_gen2ActionPerformed(evt);
            }
        });

        ComboBox_gen2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Axé", "Blues", "Country", "Eletrônica", "Forró", "Funk", "Gospel", "Hip Hop", "Jazz", "MPB", "Música clássica", "Pagode", "Pop", "Rap", "Reggae", "Rock", "Samba", "Sertanejo", "Trap" }));
        ComboBox_gen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_gen2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_nova_musicaLayout = new javax.swing.GroupLayout(jPanel_nova_musica);
        jPanel_nova_musica.setLayout(jPanel_nova_musicaLayout);
        jPanel_nova_musicaLayout.setHorizontalGroup(
            jPanel_nova_musicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_nova_musicaLayout.createSequentialGroup()
                .addGroup(jPanel_nova_musicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_nova_musicaLayout.createSequentialGroup()
                        .addGroup(jPanel_nova_musicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_nova_musicaLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(jPanel_nova_musicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label_nome)
                                    .addComponent(label_gen1)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_nova_musicaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel_nova_musicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_selc_gen2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Label_outros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_nova_musicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextField_nome)
                            .addComponent(ComboBox_gen1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextField_outros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboBox_gen2, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_nova_musicaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_limpar_musica)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salvar_musica)))
                .addContainerGap())
        );
        jPanel_nova_musicaLayout.setVerticalGroup(
            jPanel_nova_musicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_nova_musicaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel_nova_musicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_nome)
                    .addComponent(TextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_nova_musicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_gen1)
                    .addComponent(ComboBox_gen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_nova_musicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_gen2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_selc_gen2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_nova_musicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_outros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_outros))
                .addGap(18, 18, 18)
                .addGroup(jPanel_nova_musicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_limpar_musica)
                    .addComponent(btn_salvar_musica))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nova Música", jPanel_nova_musica);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Meus Gêneros"));

        Tabela_genero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela_genero.getTableHeader().setReorderingAllowed(false);
        Tabela_genero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_generoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela_genero);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btn_novo_gen.setText("Novo");
        btn_novo_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novo_genActionPerformed(evt);
            }
        });

        btn_excluir_gen.setText("Excluir");
        btn_excluir_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_genActionPerformed(evt);
            }
        });

        btn_atualizar_gen.setText("Atualizar Tabela");
        btn_atualizar_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizar_genActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Gênero"));

        ComboBox_generos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        ComboBox_generos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_generosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBox_generos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ComboBox_generos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btn_add_gen.setText("Adicionar");
        btn_add_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_genActionPerformed(evt);
            }
        });

        btn_cancelar_gen.setText("Cancelar");
        btn_cancelar_gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_genActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btn_novo_gen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_atualizar_gen)
                        .addGap(53, 53, 53)
                        .addComponent(btn_excluir_gen)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btn_cancelar_gen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_add_gen))
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_novo_gen)
                    .addComponent(btn_excluir_gen)
                    .addComponent(btn_atualizar_gen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_gen)
                    .addComponent(btn_cancelar_gen))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Gêneros Preferidos", jPanel2);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Avalie suas músicas"));

        Tabela_Avaliacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Música"
            }
        ));
        Tabela_Avaliacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_AvaliacaoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Tabela_Avaliacao);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Avaliação"));
        jPanel11.setToolTipText("");

        TextField_nota.setBorder(javax.swing.BorderFactory.createTitledBorder("Nota"));

        btn_avaliar_musica.setText("Avaliar");
        btn_avaliar_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_avaliar_musicaActionPerformed(evt);
            }
        });

        TextField_musica_avaliar.setEditable(false);
        TextField_musica_avaliar.setBorder(javax.swing.BorderFactory.createTitledBorder("Música"));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(TextField_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_avaliar_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TextField_musica_avaliar, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(TextField_musica_avaliar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField_nota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_avaliar_musica, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Avaliar Músicas", jPanel3);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Músicas Recomendadas"));

        Tabela_recomendados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        Tabela_recomendados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabela_recomendadosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Tabela_recomendados);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Adicionar Música"));

        btn_adicionar_musica.setText("Adicionar");
        btn_adicionar_musica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionar_musicaActionPerformed(evt);
            }
        });

        TextField_musica_adicionar.setEditable(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextField_musica_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_adicionar_musica, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adicionar_musica)
                    .addComponent(TextField_musica_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Gênero de Recomendação")));

        ComboBox_recomendacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        ComboBox_recomendacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_recomendacaoActionPerformed(evt);
            }
        });

        jButton2.setText("Recomendar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBox_recomendacao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_recomendacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(219, 219, 219))
        );

        jTabbedPane1.addTab("Recomendações", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salvar_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salvar_musicaActionPerformed
        // TODO add your handling code here:
        if((TextField_nome.getText().equals(""))||(ComboBox_gen1.getSelectedIndex() == 0)){
            
            JOptionPane.showMessageDialog(null,"Opa!, insira mais dados...","Opss!!", JOptionPane.WARNING_MESSAGE);
        }
        else{
            Musica m = new Musica();
            Genero g = new Genero();
            MusicaDAO dao = new MusicaDAO();
            m.setMusica(TextField_nome.getText());
            if(ComboBox_gen1.getSelectedItem().toString().equals("Outros")){
                m.setGenero1(TextField_outros.getText());
                g.setUsuario(Text_usuario.getText());
                g.setGenero(TextField_outros.getText());
                dao.creategenero(g);
            }
            else{
                m.setGenero1(ComboBox_gen1.getSelectedItem().toString());
                g.setUsuario(Text_usuario.getText());
                g.setGenero(ComboBox_gen1.getSelectedItem().toString());
                dao.creategenero(g);
            }
            if(ComboBox_gen2.getSelectedIndex()== 0){
                m.setGenero2(ComboBox_gen1.getSelectedItem().toString());
                g.setUsuario(Text_usuario.getText());
                g.setGenero(ComboBox_gen1.getSelectedItem().toString());
                dao.creategenero(g);
            }
            else{
                m.setGenero2(ComboBox_gen2.getSelectedItem().toString());
                g.setUsuario(Text_usuario.getText());
                g.setGenero(ComboBox_gen2.getSelectedItem().toString());
                dao.creategenero(g);
            }
            m.setUsuario(Text_usuario.getText());
            m.setNota(0);
            dao.create(m);
            dao.limpagenero();
        }
        LoadComboBoxGen();
        LoadTabelaAvaliacao();
        
    }//GEN-LAST:event_btn_salvar_musicaActionPerformed

    private void btn_limpar_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpar_musicaActionPerformed
        // TODO add your handling code here:
        TextField_nome.setText("");
        ComboBox_gen1.setSelectedIndex(0);
        TextField_outros.setText("");
        TextField_outros.setEnabled(false);
        ComboBox_gen2.setEnabled(false);
        btn_selc_gen2.setSelected(false);
        ComboBox_gen2.setSelectedIndex(0);
    }//GEN-LAST:event_btn_limpar_musicaActionPerformed

    private void btn_novo_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novo_genActionPerformed
        // TODO add your handling code here:
        ManipulacaoInterfase("Novo");
        MusicaDAO dao = new MusicaDAO();
        dao.limpaGeneroPreferido();
    }//GEN-LAST:event_btn_novo_genActionPerformed

    private void ComboBox_gen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_gen1ActionPerformed
        // TODO add your handling code here:
        if(ComboBox_gen1.getSelectedItem().toString().equals("Outros")){
            TextField_outros.setEnabled(true);   
        }
    }//GEN-LAST:event_ComboBox_gen1ActionPerformed

    private void btn_selc_gen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_selc_gen2ActionPerformed
        // TODO add your handling code here:
        ComboBox_gen2.setEnabled(true);
    }//GEN-LAST:event_btn_selc_gen2ActionPerformed

    private void ComboBox_gen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_gen2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_gen2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TextField_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_nomeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TextField_nomeActionPerformed

    private void btn_atualizar_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizar_genActionPerformed
        // TODO add your handling code here:
        MusicaDAO dao = new MusicaDAO();
        dao.limpaGeneroPreferido();
        LoadTabelaGen();
    }//GEN-LAST:event_btn_atualizar_genActionPerformed

    private void btn_add_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_genActionPerformed
        // TODO add your handling code here:
        if(ComboBox_generos.getSelectedIndex()!=0){
            Genero gen = new Genero();
            MusicaDAO dao = new MusicaDAO();
            gen.setUsuario(Text_usuario.getText());
            gen.setGenero(ComboBox_generos.getSelectedItem().toString());
            dao.createTbGenero(gen);
            ComboBox_generos.setEnabled(false);
            btn_add_gen.setEnabled(false);
            btn_cancelar_gen.setEnabled(false);
            LoadTabelaGen();
            dao.limpaGeneroPreferido();
        }
        else{
            JOptionPane.showMessageDialog(null,"Selecione um gênero...","Opss!!", JOptionPane.WARNING_MESSAGE);
        }
        ManipulacaoInterfase("Navegar");
    }//GEN-LAST:event_btn_add_genActionPerformed

    private void btn_cancelar_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_genActionPerformed
        // TODO add your handling code here:
        ManipulacaoInterfase("Navegar");
    }//GEN-LAST:event_btn_cancelar_genActionPerformed

    private void ComboBox_generosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_generosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_generosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //MusicaDAO dao = new MusicaDAO();
        //dao.readRecomendadas(ComboBox_recomendacao.getSelectedItem().toString());
        LoadTabelaRecomendada();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    String genExcluir;
    
    private void Tabela_generoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_generoMouseClicked
        // TODO add your handling code here:\
        int index = Tabela_genero.getSelectedRow();  
        MusicaDAO dao = new MusicaDAO();
        if(index >= 0 && index < dao.readGenPref(Text_usuario.getText()).size()){
            ManipulacaoInterfase("Excluir");
            GeneroPreferido g = dao.readGenPref(Text_usuario.getText()).get(index);//genList.get(index);
            genExcluir = g.getGenero();
            
        }
        
    }//GEN-LAST:event_Tabela_generoMouseClicked

    private void btn_excluir_genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_genActionPerformed
        // TODO add your handling code here:
        MusicaDAO dao = new MusicaDAO();
        dao.deleteGeneroPref(Text_usuario.getText(),genExcluir);
        LoadTabelaGen();
    }//GEN-LAST:event_btn_excluir_genActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void btn_avaliar_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_avaliar_musicaActionPerformed
        int index = Tabela_Avaliacao.getSelectedRow();
        MusicaDAO dao = new MusicaDAO();
        if(index >= 0 && index < dao.readAvaliacao(Text_usuario.getText()).size()){
            dao.insertNota(parseDouble(TextField_nota.getText()), TextField_musica_avaliar.getText(), Text_usuario.getText());
        }
        LoadTabelaAvaliacao();
    }//GEN-LAST:event_btn_avaliar_musicaActionPerformed

    private void Tabela_AvaliacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_AvaliacaoMouseClicked
        DefaultTableModel modelo = (DefaultTableModel)Tabela_Avaliacao.getModel();
        int selectedRowIndex = Tabela_Avaliacao.getSelectedRow();
        TextField_musica_avaliar.setText(modelo.getValueAt(selectedRowIndex, 0).toString());
    }//GEN-LAST:event_Tabela_AvaliacaoMouseClicked
                                      
    private void btn_adicionar_musicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionar_musicaActionPerformed
       MusicaDAO dao = new MusicaDAO();
       DefaultTableModel modelo = (DefaultTableModel)Tabela_recomendados.getModel();
       int selectedRowIndex = Tabela_recomendados.getSelectedRow();
       dao.adcMusica(Text_usuario.getText(), ComboBox_recomendacao.getSelectedItem().toString(), modelo.getValueAt(selectedRowIndex, 0).toString(), 0.0);
       LoadTabelaAvaliacao();
       modelo.removeRow(selectedRowIndex);

    }//GEN-LAST:event_btn_adicionar_musicaActionPerformed

    private void Tabela_recomendadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabela_recomendadosMouseClicked
        DefaultTableModel modelo = (DefaultTableModel)Tabela_recomendados.getModel();
        int selectedRowIndex = Tabela_recomendados.getSelectedRow();
        TextField_musica_adicionar.setText(modelo.getValueAt(selectedRowIndex, 0).toString());
    }//GEN-LAST:event_Tabela_recomendadosMouseClicked

    private void jTabbedPane1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane1FocusGained
        // TODO add your handling code here:
        LoadTabelaGen();
        LoadTabelaAvaliacao();
        LoadTabelaRecomendada();          
    }//GEN-LAST:event_jTabbedPane1FocusGained

    private void ComboBox_recomendacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_recomendacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_recomendacaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_gen1;
    private javax.swing.JComboBox<String> ComboBox_gen2;
    private javax.swing.JComboBox<Object> ComboBox_generos;
    private javax.swing.JComboBox<String> ComboBox_recomendacao;
    private javax.swing.JLabel Label_outros;
    private javax.swing.JTable Tabela_Avaliacao;
    private javax.swing.JTable Tabela_genero;
    private javax.swing.JTable Tabela_recomendados;
    private javax.swing.JTextField TextField_musica_adicionar;
    private javax.swing.JTextField TextField_musica_avaliar;
    private javax.swing.JTextField TextField_nome;
    private javax.swing.JTextField TextField_nota;
    private javax.swing.JTextField TextField_outros;
    private javax.swing.JLabel Text_usuario;
    private javax.swing.JButton btn_add_gen;
    private javax.swing.JButton btn_adicionar_musica;
    private javax.swing.JButton btn_atualizar_gen;
    private javax.swing.JButton btn_avaliar_musica;
    private javax.swing.JButton btn_cancelar_gen;
    private javax.swing.JButton btn_excluir_gen;
    private javax.swing.JButton btn_limpar_musica;
    private javax.swing.JButton btn_novo_gen;
    private javax.swing.JButton btn_salvar_musica;
    private javax.swing.JRadioButton btn_selc_gen2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_nova_musica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label_gen1;
    private javax.swing.JLabel label_nome;
    // End of variables declaration//GEN-END:variables
    public void recebeUsuario(String textoUsuario){
        Text_usuario.setText(textoUsuario);
    }
}

